### ISSUE TITLE
Fix undo/redo history bug

### ISSUE THREAD

**Issue by davekinkead** [davekinkead/reasons#18]
> One maybe bug I've found is that the undo stack remembers the panning offset/zoom levels (since these values are being updated on the node x/y's instead of just at draw time ... I'll take a look at moving the scaling/panning value adjustments to the canvas drawing code.

Agree @geoffreyd - the only thing that should be added to history is x&y on node move, not pan or zoom.

**Comment by geoffreyd** [comment]
I think I've fixed this in previous updates, could you check and update if it's not behaving as expected?

**Comment by davekinkead** [comment]
Looks good - behaving as expected
